spring:
  profiles:
    active: postgres
  datasource:
    name: postgres
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: pass
    hikari:
      poolName: Hikari
      auto-commit: false
